# Generated by Django 4.2.5 on 2023-09-06 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "city", "verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "country", "verbose_name_plural": "countries"},
        ),
        migrations.RenameField(
            model_name="flight",
            old_name="crew",
            new_name="crews",
        ),
    ]
